# Valores usados en actions (executeTvTimeline p.ej.) para generar el xml 
# del timeline y en indexDashSuccess para pintar la leyenda de la página
all:
  destacados_tv:
    color:          '#50AA50'
  destacados_radio:
    color:          '#0000FF'
