# previewallSuccess:
#   stylesheets:    [tv/default, css]

all:
  stylesheets:    [/sf/calendar/calendar-system.css, /sf/calendar/skins/aqua/theme.css, admin/accordion.css, admin/tree]
  javascripts:    [/sf/calendar/calendar.js, /sf/calendar/lang/calendar-es.js, /sf/calendar/calendar-setup.js, accordion.js, tree, /js/jquery-1.8.3.min.js]

timelineSuccess:
  stylesheets:    [admin/dashboard]
  javascripts:    [/js/timeline_2.3.1/timeline_js/timeline-api.js]

  has_layout: off

  http_metas:
    content-type: text/xml

indexDashSuccess:
  stylesheets:    [admin/dashboard]
  javascripts:    [/js/timeline_2.3.1/timeline_js/timeline-api.js]

  #has_layout: off

  # http_metas:
  #   content-type: text/xml
# see editar/modules/dashboard/config/view.yml "infopdfSuccess" section.