all:
  propel:
    class:                sfPropelDatabase
    param:
      phptype:            mysql     # Database vendor
      hostspec:           localhost
      database:           pumukit
      username:           pmk_user
      password:           pmk_password
      port:               3306
      encoding:           utf8
      persistent:         true
