default:
  http_metas:
    content-type: text/html

  metas:
    title:        Editar WEB
    robots:       index, follow
    description:  Edit data base of Pumukit
    keywords:     pumukit, DDBB
    language:     es

  stylesheets:    [main, admin/cab, admin/menu, admin/modalbox, admin/admin]

  javascripts:    [prototype, scriptaculous, effects, modalbox, js, admin/validate]

  has_layout:     on
  layout:         layout
